/**
 * Instinct vs Insight — Scenario Bank (v2)
 * 32 entries. Each has: situation, instincts (3), feelings (3), starters (2), category.
 */
export const INSTINCT_SCENARIOS = [
  { id: 1, category: 'relationships', situation: "Someone doesn't respond to your text for a few hours.", instincts: ["Check if I said something wrong", "Send a follow-up text", "Assume they're ignoring me"], feelings: ['Anxious', 'Rejected', 'Impatient'], starters: ["Maybe they're just in the middle of something and haven't seen it yet.", "People go quiet for all kinds of reasons that have nothing to do with me."] },
  { id: 2, category: 'relationships', situation: "A friend cancels plans on you last minute for the second time in a row.", instincts: ["They don't really care about spending time with me", "I shouldn't have expected them to show up", "I'm always the one who cares more"], feelings: ['Hurt', 'Frustrated', 'Unimportant'], starters: ["Life gets messy sometimes, and this might just be a rough patch for them.", "I can be disappointed without deciding this means they don't care."] },
  { id: 3, category: 'self-worth', situation: "You make a small mistake in front of coworkers during a meeting.", instincts: ["Everyone thinks I'm incompetent", "I need to overexplain what happened", "I should have just stayed quiet"], feelings: ['Embarrassed', 'Exposed', 'Small'], starters: ["Everyone messes up in front of others sometimes, it's not the disaster it feels like.", "One slip doesn't erase everything I've actually gotten right."] },
  { id: 4, category: 'self-worth', situation: "Someone gives you feedback that stings more than you expected.", instincts: ["They're saying I'm not good enough", "I need to defend myself right now", "I'll just avoid this kind of work going forward"], feelings: ['Defensive', 'Ashamed', 'Deflated'], starters: ["Feedback about my work isn't a verdict on who I am as a person.", "I can take this seriously without taking it as proof I'm not good enough."] },
  { id: 5, category: 'fear/anxiety', situation: "You're about to have a conversation you've been putting off because it feels risky.", instincts: ["This is going to go badly", "I should just avoid it longer", "I'm not ready for this"], feelings: ['Dread', 'Nervous', 'On edge'], starters: ["The version of this I've built up in my head is probably worse than what actually happens.", "I can be nervous and still walk in and say what I need to say."] },
  { id: 6, category: 'fear/anxiety', situation: "You notice your heart racing before a presentation or big moment.", instincts: ["Something's wrong with me", "Everyone will see I'm nervous", "I'm going to mess this up"], feelings: ['Panicked', 'Shaky', 'Overwhelmed'], starters: ["This is just my body gearing up, not a sign that something's about to go wrong.", "Feeling keyed up doesn't mean I'm not actually ready for this."] },
  { id: 7, category: 'control/perfectionism', situation: "A project doesn't turn out exactly how you planned it, even though it still worked.", instincts: ["This isn't good enough", "I need to redo it", "It's basically a failure"], feelings: ['Disappointed', 'Restless', 'Unsatisfied'], starters: ["Good enough and done is sometimes worth more than perfect and never finished.", "This still counts as a win even if it didn't match the picture in my head."] },
  { id: 8, category: 'control/perfectionism', situation: "You catch yourself redoing something for the third time because it still doesn't feel right.", instincts: ["It's still not right", "I can't let this go until it's perfect", "If I don't fix it, it'll bother me all day"], feelings: ['Uneasy', 'Obsessive', 'Never satisfied'], starters: ["At some point, more effort stops improving this and starts just delaying me.", "I can let this be finished without it being flawless."] },
  { id: 9, category: 'purpose/identity', situation: "You compare where you are in life to where a friend or peer already is.", instincts: ["I'm so far behind", "I should be further along by now", "They're doing better than me"], feelings: ['Behind', 'Inadequate', 'Discouraged'], starters: ["Their timeline isn't proof of anything about mine.", "I'm allowed to be exactly where I am without treating it like I'm behind."] },
  { id: 10, category: 'purpose/identity', situation: "You're not sure what you actually want anymore in a season that used to feel clear.", instincts: ["I've lost my way", "I should have figured this out by now", "Something's wrong with me for not knowing"], feelings: ['Lost', 'Unsettled', 'Ashamed of not knowing'], starters: ["Not having it figured out right now doesn't mean I've lost it for good.", "Seasons where things feel unclear are still part of getting somewhere, not proof I've stalled."] },
  { id: 11, category: 'relationships', situation: "Someone close to you seems distant or short with you lately, and you don't know why.", instincts: ["I must have done something wrong", "They're pulling away from me", "I should give them space before I get hurt"], feelings: ['Confused', 'Anxious', 'On guard'], starters: ["Whatever's going on with them might not have anything to do with me at all.", "I can ask what's going on instead of quietly building a story in my head."] },
  { id: 12, category: 'self-worth', situation: "You didn't get picked for something you really wanted.", instincts: ["I'm not good enough", "They don't see my value", "I shouldn't have even tried"], feelings: ['Rejected', 'Disappointed', 'Discouraged'], starters: ["Not being chosen this time doesn't mean I wasn't good enough to be chosen.", "There's a difference between this wasn't the right fit and I'm not enough."] },
  { id: 13, category: 'fear/anxiety', situation: "You're waiting on results or news that could go either way.", instincts: ["It's going to be bad news", "I should prepare for the worst", "Something's going to go wrong"], feelings: ['Anxious', 'Restless', 'On edge'], starters: ["However this turns out, I'll actually be able to handle it when it gets here.", "The waiting is the hardest part, and it doesn't mean the outcome is already bad."] },
  { id: 14, category: 'control/perfectionism', situation: "You have to hand off a task to someone else and let them do it their own way.", instincts: ["They're going to mess it up", "I should just do it myself", "It won't be done right"], feelings: ['Uneasy', 'Distrustful', 'Anxious'], starters: ["It doesn't have to be done exactly like I'd do it to still get done well.", "Letting go of this doesn't mean it falls apart without me."] },
  { id: 15, category: 'purpose/identity', situation: "You feel like you're starting over in an area of life you thought you'd already figured out.", instincts: ["I failed", "I'm back at square one", "I wasted all that time"], feelings: ['Defeated', 'Embarrassed', 'Discouraged'], starters: ["Starting again isn't the same as never having made any progress at all.", "This chapter can look different from the last one without meaning I failed the last one."] },
  { id: 16, category: 'relationships', situation: "You say something in a conversation and immediately worry it came out wrong.", instincts: ["They're judging me now", "I need to explain what I meant", "I always say the wrong thing"], feelings: ['Embarrassed', 'Anxious', 'Self-conscious'], starters: ["One awkward moment isn't the thing this whole relationship is going to be remembered by.", "I can circle back and clarify instead of assuming the damage is already done."] },
  { id: 17, category: 'self-worth', situation: "You scroll social media and end up feeling worse about your own life.", instincts: ["Everyone's life is better than mine", "I'm so far behind", "I'll never have what they have"], feelings: ['Inadequate', 'Envious', 'Discouraged'], starters: ["What I'm seeing is a highlight reel, not the full picture of anyone's actual life.", "Their good moment doesn't take anything away from what's actually true about mine."] },
  { id: 18, category: 'fear/anxiety', situation: "You have to make a decision without knowing exactly how it's going to turn out.", instincts: ["I'm probably going to choose wrong", "I should wait until I'm sure", "What if this is a mistake"], feelings: ['Uncertain', 'Anxious', 'Overwhelmed'], starters: ["I don't need certainty to make a decision I can stand behind.", "Not knowing the outcome yet doesn't mean I'm choosing wrong."] },
  { id: 19, category: 'control/perfectionism', situation: "Plans you organized fall apart because of something outside your control.", instincts: ["I should have planned better", "This is my fault somehow", "I can't let go of what went wrong"], feelings: ['Frustrated', 'Responsible', 'Anxious'], starters: ["This going sideways isn't evidence that I didn't plan it well enough.", "Some things were never going to be mine to control in the first place."] },
  { id: 20, category: 'purpose/identity', situation: "You turn down an opportunity that would've looked good on paper but didn't feel right.", instincts: ["I'm wasting my potential", "I'm making a mistake", "People will think I'm lazy"], feelings: ['Uncertain', 'Guilty', 'Anxious'], starters: ["Saying no to something impressive doesn't mean I'm wasting my potential.", "What looks right for someone else isn't automatically what's right for me."] },
  { id: 21, category: 'faith-based', situation: "You're praying or hoping for something and the answer still hasn't come.", instincts: ["God's not listening", "I must be doing something wrong", "Maybe it's a no"], feelings: ['Discouraged', 'Impatient', 'Doubtful'], starters: ["Silence right now doesn't mean the answer is no, it might just not be time yet.", "I can keep trusting the process even in the part where nothing seems to be happening."] },
  { id: 22, category: 'faith-based', situation: "You feel like you've fallen short of who you're trying to become.", instincts: ["I'm not who I'm supposed to be", "I keep failing at this", "I'll never get there"], feelings: ['Ashamed', 'Discouraged', 'Defeated'], starters: ["One off day doesn't cancel out the direction I'm actually walking in.", "Grace covers this stumble the same way it's covered every one before it."] },
  { id: 23, category: 'relationships', situation: "You have to set a boundary with someone you care about, and you're worried how they'll take it.", instincts: ["I'm being selfish", "They're going to be upset with me", "Maybe I shouldn't have said anything"], feelings: ['Guilty', 'Anxious', 'Torn'], starters: ["A boundary isn't me pulling away from them, it's me staying in this relationship honestly.", "Their reaction to my boundary tells me something about them, not something wrong about me for having it."] },
  { id: 24, category: 'self-worth', situation: "You accomplish something and immediately downplay it instead of letting it count.", instincts: ["It's not that big a deal", "Anyone could have done it", "I don't deserve to celebrate"], feelings: ['Uncomfortable', 'Undeserving', 'Restless'], starters: ["I'm allowed to actually let this be a win instead of talking myself out of it.", "Brushing this off doesn't make me humble, it just makes me miss my own progress."] },
  { id: 25, category: 'fear/anxiety', situation: "You avoid checking something (an email, a message, a number) because you're scared of what you'll find.", instincts: ["It's going to be bad", "I can't handle what I'll find", "If I don't look, it's not real yet"], feelings: ['Dread', 'Anxious', 'Avoidant'], starters: ["Whatever it says, I can handle knowing it more than I can handle not knowing.", "Avoiding it doesn't make it not true, it just makes the waiting longer."] },
  { id: 26, category: 'control/perfectionism', situation: "Someone points out a flaw in something you worked hard on.", instincts: ["They're right, this is bad", "I should have caught that", "The whole thing is ruined now"], feelings: ['Stung', 'Defensive', 'Discouraged'], starters: ["One flaw doesn't undo everything else that's actually working in this.", "I can fix what needs fixing without treating the whole thing as ruined."] },
  { id: 27, category: 'purpose/identity', situation: "You feel pulled toward a change that would disappoint people who expect you to stay the same.", instincts: ["I'm letting them down", "They'll think I'm being selfish", "I should just stay the same"], feelings: ['Torn', 'Guilty', 'Anxious'], starters: ["Their expectations were never supposed to be the ceiling on who I become.", "I can love people and still choose differently than what they pictured for me."] },
  { id: 28, category: 'relationships', situation: "You find out about plans you weren't included in.", instincts: ["They don't want me around", "I'm being pushed out", "Nobody really cares if I'm there"], feelings: ['Hurt', 'Excluded', 'Insecure'], starters: ["Not being included this one time isn't proof I'm being pushed out.", "I can feel left out without turning it into a verdict on the whole friendship."] },
  { id: 29, category: 'self-worth', situation: "You're the only one who didn't finish, win, or succeed in a group setting.", instincts: ["Everyone noticed I failed", "I'm the weakest one here", "I don't belong at this level"], feelings: ['Embarrassed', 'Inadequate', 'Isolated'], starters: ["Where I landed this time isn't the whole story of what I'm capable of.", "Everyone's on a different timeline, and mine isn't behind just because it's different."] },
  { id: 30, category: 'fear/anxiety', situation: "You wake up already dreading something later in the day.", instincts: ["Today is going to be awful", "I can't handle what's coming", "I just want to get through this"], feelings: ['Dread', 'Heavy', 'On edge'], starters: ["The dread showing up early doesn't mean the day is already decided.", "I can feel the nerves now and still have this go completely fine later."] },
  { id: 31, category: 'faith-based', situation: "You're carrying something heavy and trying to hold it together on your own.", instincts: ["I should be able to handle this", "Asking for help means I'm weak", "I can't burden anyone with this"], feelings: ['Exhausted', 'Alone', 'Overwhelmed'], starters: ["I wasn't actually built to carry this by myself, and setting it down isn't giving up.", "Asking for help with this is still allowed, even this far into carrying it alone."] },
  { id: 32, category: 'control/perfectionism', situation: "You're tempted to stay up late fixing something that's already good enough.", instincts: ["It's not done yet", "If I don't fix it now, it'll bother me", "Rest can wait until it's right"], feelings: ['Restless', 'Guilty', 'Driven'], starters: ["Rest is part of doing this well, not something standing in the way of it.", "This can wait until tomorrow without falling apart overnight."] },
];

export function getRandomScenario(excludeIds = []) {
  const pool = INSTINCT_SCENARIOS.filter(s => !excludeIds.includes(s.id));
  const pick = pool.length > 0 ? pool : INSTINCT_SCENARIOS;
  return pick[Math.floor(Math.random() * pick.length)];
}